[2025-05-21T09:50:00.983+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_and_store scheduled__2025-05-21T09:45:00+00:00 [queued]>
[2025-05-21T09:50:00.987+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_snowflake.consume_and_store scheduled__2025-05-21T09:45:00+00:00 [queued]>
[2025-05-21T09:50:00.987+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-05-21T09:50:00.992+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_and_store> on 2025-05-21 09:45:00+00:00
[2025-05-21T09:50:00.996+0000] {standard_task_runner.py:57} INFO - Started process 963 to run task
[2025-05-21T09:50:00.999+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_snowflake', 'consume_and_store', 'scheduled__2025-05-21T09:45:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_snowflake.py', '--cfg-path', '/tmp/tmprf2a2ugs']
[2025-05-21T09:50:01.001+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask consume_and_store
[2025-05-21T09:50:01.011+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:50:01.035+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_to_snowflake.consume_and_store scheduled__2025-05-21T09:45:00+00:00 [running]> on host 181c87754ed7
[2025-05-21T09:50:01.076+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_snowflake' AIRFLOW_CTX_TASK_ID='consume_and_store' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T09:45:00+00:00'
[2025-05-21T09:50:01.078+0000] {kafka_to_snowflake.py:60} INFO - Starting Kafka → Snowflake ingestion for 2025-05-21 09:45:00 → 2025-05-21 09:50:00 UTC
[2025-05-21T09:50:01.079+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=kafka:29092 <connecting> [IPv4 ('172.18.0.3', 29092)]>: connecting to kafka:29092 [('172.18.0.3', 29092) IPv4]
[2025-05-21T09:50:01.087+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=kafka:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.3', 29092)]>: Broker version identified as 2.6
[2025-05-21T09:50:01.087+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Connection complete.
[2025-05-21T09:50:01.089+0000] {subscription_state.py:177} INFO - Updating subscribed topics to: ('flights',)
[2025-05-21T09:50:01.092+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1001 host=kafka:29092 <connecting> [IPv4 ('172.18.0.3', 29092)]>: connecting to kafka:29092 [('172.18.0.3', 29092) IPv4]
[2025-05-21T09:50:01.092+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1001 host=kafka:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Connection complete.
[2025-05-21T09:50:01.093+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=bootstrap-0 host=kafka:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Closing connection. 
[2025-05-21T09:50:01.649+0000] {cluster.py:400} INFO - Coordinator for group/***_kafka_to_snowflake is ('coordinator-1001', 'kafka', 29092, None)
[2025-05-21T09:50:01.650+0000] {base.py:769} INFO - Discovered coordinator coordinator-1001 for group ***_kafka_to_snowflake
[2025-05-21T09:50:01.650+0000] {base.py:820} INFO - Starting new heartbeat thread
[2025-05-21T09:50:01.651+0000] {consumer.py:362} INFO - Revoking previously assigned partitions () for group ***_kafka_to_snowflake
[2025-05-21T09:50:01.652+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1001 host=kafka:29092 <connecting> [IPv4 ('172.18.0.3', 29092)]>: connecting to kafka:29092 [('172.18.0.3', 29092) IPv4]
[2025-05-21T09:50:01.652+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1001 host=kafka:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Connection complete.
[2025-05-21T09:50:01.755+0000] {base.py:524} INFO - (Re-)joining group ***_kafka_to_snowflake
[2025-05-21T09:50:01.785+0000] {base.py:524} INFO - (Re-)joining group ***_kafka_to_snowflake
[2025-05-21T09:50:04.810+0000] {base.py:587} INFO - Elected group leader -- performing partition assignments using range
[2025-05-21T09:50:04.830+0000] {base.py:401} INFO - Successfully joined group ***_kafka_to_snowflake with generation 1
[2025-05-21T09:50:04.831+0000] {subscription_state.py:246} INFO - Updated partition assignment: [('flights', 0)]
[2025-05-21T09:50:04.831+0000] {consumer.py:249} INFO - Setting newly assigned partitions (('flights', 0),) for group ***_kafka_to_snowflake
[2025-05-21T09:50:04.840+0000] {fetcher.py:413} INFO - Resetting offset for partition ('flights', 0) to offset 0.
[2025-05-21T09:50:15.018+0000] {base.py:834} INFO - Stopping heartbeat thread
[2025-05-21T09:50:18.022+0000] {base.py:1037} WARNING - Heartbeat thread did not fully terminate during close
[2025-05-21T09:50:18.024+0000] {base.py:865} INFO - Leaving consumer group (***_kafka_to_snowflake).
[2025-05-21T09:50:18.059+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=1001 host=kafka:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Closing connection. 
[2025-05-21T09:50:18.062+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.7, node_id=coordinator-1001 host=kafka:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Closing connection. 
[2025-05-21T09:50:18.063+0000] {kafka_to_snowflake.py:87} INFO - Consumed 4300 messages from Kafka
[2025-05-21T09:50:18.066+0000] {connection.py:334} INFO - Snowflake Connector for Python Version: 3.3.1, Python Version: 3.8.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.17
[2025-05-21T09:50:18.075+0000] {connection.py:1103} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-21T09:50:18.076+0000] {connection.py:1121} INFO - Setting use_openssl_only mode to False
[2025-05-21T09:50:19.475+0000] {cursor.py:833} INFO - query: [INSERT INTO PUBLIC.aircraft_raw (icao24, callsign, origin_country, longitude, la...]
[2025-05-21T09:50:23.379+0000] {cursor.py:846} INFO - query execution done
[2025-05-21T09:50:23.393+0000] {kafka_to_snowflake.py:108} INFO - Inserted 4300 raw rows
[2025-05-21T09:50:23.394+0000] {cursor.py:833} INFO - query: [INSERT INTO PUBLIC.aircraft_summary (run_time, origin_country, aircraft_count, a...]
[2025-05-21T09:50:24.123+0000] {cursor.py:846} INFO - query execution done
[2025-05-21T09:50:24.124+0000] {kafka_to_snowflake.py:126} INFO - Inserted 23 summary rows
[2025-05-21T09:50:24.124+0000] {cursor.py:833} INFO - query: [COMMIT]
[2025-05-21T09:50:24.353+0000] {cursor.py:846} INFO - query execution done
[2025-05-21T09:50:24.353+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2025-05-21T09:50:24.354+0000] {connection.py:677} INFO - closed
[2025-05-21T09:50:24.572+0000] {connection.py:683} INFO - No async queries seem to be running, deleting session
[2025-05-21T09:50:24.990+0000] {kafka_to_snowflake.py:51} INFO - Telegram notification sent: ✅ *Data ingestion complete* for 2025-05-21 09:45:00 → 2025-05-21 09:50:00 UTC | • Events sent: *4300* | • Countries summarized: *23*
[2025-05-21T09:50:24.992+0000] {kafka_to_snowflake.py:146} INFO - Done.
[2025-05-21T09:50:24.998+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-21T09:50:25.025+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=kafka_to_snowflake, task_id=consume_and_store, execution_date=20250521T094500, start_date=20250521T095000, end_date=20250521T095025
[2025-05-21T09:50:25.060+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T09:50:25.082+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
